global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai-monitor"
    static_configs:
      - targets: ["ai-monitor:3333"]
    metrics_path: "/metrics"
    scrape_interval: 10s
